image: node:10.15.3

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  services:
    docker:
      memory: 2048
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - sonar
        script:
          - npm install --quiet
          - npm run build-prod
          - pipe: sonarsource/sonarcloud-scan:1.2.1
            variables:
              SONAR_SCANNER_OPTS: -Xmx2048m
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.sources=projects/oc-ng-common-component/src -Dsonar.tests=projects/oc-ng-common-component/src -Dsonar.test.inclusions="**/testing/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
    - step: &build-and-push-new-version-of-services
        name: Push services to npm
        script:
          - npm install --quiet
          - npm run build-prod oc-ng-common-service
          - npm run oc-ng-common-service-pack
          - pipe: atlassian/npm-publish:0.3.2
            variables:
              NPM_TOKEN: $NPM_TOKEN
              FOLDER: 'projects/oc-ng-common-service'
              EXTRA_ARGS: '--access public'
    - step: &build-and-push-new-version-of-components
        name: Push components to npm
        script:
          - npm install --quiet
          - npm run build-prod oc-ng-common-component
          - npm run oc-ng-common-component-pack
          - pipe: atlassian/npm-publish:0.3.2
            variables:
              NPM_TOKEN: $NPM_TOKEN
              FOLDER: 'projects/oc-ng-common-component'
              EXTRA_ARGS: '--access public'
    - step: &push-to-github
        name: Push to GitHub
        script:
          - git remote set-url origin git@github.com:openchannel/angular-template-libraries.git
          - git remote -v
          - git push origin master:main
          - git push origin --tags

pipelines:
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
  custom:
    publish-components:
      - step: *build-and-push-new-version-of-components
    publish-services:
      - step: *build-and-push-new-version-of-services
  branches:
    develop:
      - step: *build-test-sonarcloud
    release/*:
      - step: *build-test-sonarcloud
    master:
      - step: *build-test-sonarcloud
      - step: *push-to-github
      - parallel:
          - step: *build-and-push-new-version-of-services
          - step: *build-and-push-new-version-of-components
