image: node:10.15.3

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - sonar
        script:
          - npm install --quiet
          - pipe: sonarsource/sonarcloud-scan:0.1.5
            variables:
              SONAR_SCANNER_OPTS: -Xmx1024m
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.sources=projects/oc-ng-common-component/src -Dsonar.tests=projects/oc-ng-common-component/src -Dsonar.test.inclusions="**/testing/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
    - step: &new-version
        name: Create new version of library and commit
        script:
          - echo "Made a change in build ${BITBUCKET_BUILD_NUMBER}"
          - npm run oc-ng-common-component-up-version
          - git commit -a -m "Auto increment prerelease version [skip ci]"
          - git push
          - npm install
          - npm run build-prod
          - npm run oc-ng-common-component-pack
        artifacts:
          - dist/**
    - step: &push-new-version
        name: Push library to repository
        script:
          - pipe: cloudsmith-io/publish:0.3.0
            variables:
              CLOUDSMITH_REPOSITORY: 'openchannel/angular-common-components'
              CLOUDSMITH_API_KEY: $CLOUDSMITH_API_KEY
              PACKAGE_FORMAT: 'npm'
              PACKAGE_NPM_DIST_TAG: 'stable'
              PACKAGE_PATH: 'dist/oc-ng-common-component/*.tgz'
              REPUBLISH: 'true'

pipelines:
  default:
    - step:
        name: Build
        script:
          - npm install
          - npm run build-prod
  branches:
    develop:
      - step: *new-version
      - step: *push-new-version

    AT-117_angular_templates:
      - step: *new-version
      - step: *push-new-version
