image: node:10.15.3

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  services:
    docker:
      memory: 2048
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - sonar
        script:
          - npm install --quiet
          - npm run build-prod
          - pipe: sonarsource/sonarcloud-scan:1.2.1
            variables:
              SONAR_SCANNER_OPTS: -Xmx2048m
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.sources=projects/oc-ng-common-component/src -Dsonar.tests=projects/oc-ng-common-component/src -Dsonar.test.inclusions="**/testing/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
    - step: &build-and-push-new-version
        name: Push library to repository
        script:
          - npm install --quiet
          - npm run build-prod
          - npm run oc-ng-common-service-pack
          - npm run oc-ng-common-component-pack
          - pipe: cloudsmith-io/publish:0.3.0
            variables:
              CLOUDSMITH_REPOSITORY: 'openchannel/angular-common-components'
              CLOUDSMITH_API_KEY: $CLOUDSMITH_API_KEY
              PACKAGE_FORMAT: 'npm'
              PACKAGE_NPM_DIST_TAG: 'stable'
              PACKAGE_PATH: 'dist/oc-ng-common-component/*.tgz'
              REPUBLISH: 'true'
    - step: &increase-version
        name: Up library version
        script:
          - echo "Made a change in build ${BITBUCKET_BUILD_NUMBER}"
          - npm run oc-ng-common-service-up-version
          - npm run oc-ng-common-component-up-version
          - git commit -a -m "Auto increment prerelease version [skip ci]"
          - git push
pipelines:
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
  custom:
    publish:
      - step: *build-and-push-new-version
  branches:
    develop:
      - step: *build-test-sonarcloud
      - step:
          trigger: manual
          <<: *increase-version
          <<: *build-and-push-new-version
    release/*:
      - step: *build-test-sonarcloud
      - step:
          trigger: manual
          <<: *increase-version
          <<: *build-and-push-new-version
