image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build
        #        caches:
        #          - node
        script:
          - npm install
          - npm run build
    - step:
        name: Bump version
        script:
          - echo "Made a change in build ${BITBUCKET_BUILD_NUMBER}"
          - npm run oc-ng-common-component-up-version
          - git commit -a -m "Auto increment prerelease version [skip ci]"
          - git push
    - step:
        name: Push library to repository
        script:
          - npm install
          - npm run build
          - npm run oc-ng-common-component-pack
          - pipe: cloudsmith-io/publish:0.3.0
            variables:
              CLOUDSMITH_REPOSITORY: 'openchannel/angular-common-components'
              CLOUDSMITH_API_KEY: $CLOUDSMITH_API_KEY
              PACKAGE_FORMAT: 'npm'
              PACKAGE_NPM_DIST_TAG: 'stable'
              PACKAGE_PATH: 'dist/oc-ng-common-component/*.tgz'
              REPUBLISH: 'true'